### ISSUE TITLE
Back button disabled

### ISSUE THREAD

**Issue by hentrev** [medienbaecker/kirby-link-field#16]
The back button in the header of the field is disabled and not visible at all. The result is that it is impossible to go back in the page hierarchy when selecting an internal page.

Saw the issue while working on a client website. Could reproduce it myself with the kirby starterkit-master.

I can see the back button being disabled in the devtools so might be just an issue of configuration. Since I don't have any experience with the kirby UI-Kit, I cannot provide a pull request at the moment though.

**Comment by hentrev** [comment]
Hi @medienbaecker, did you have time to check the issue? Would be great. Best regards, Henrik

**Comment by medienbaecker** [comment]
@hentrev Sorry for the wait. Since Kirby added the [conditional fields](https://getkirby.com/docs/guide/blueprints/fields#conditional-fields) in 3.1.0, I personally used a simple select instead of this link field in my projects.

![link-v2](https://user-images.githubusercontent.com/7975568/64112439-b3109c00-cd87-11e9-8229-0b710e2fa4cc.gif)

Since it's possible to register blueprints in plugins, I published this in a v2 branch: https://github.com/medienbaecker/kirby-link-field/tree/v2

Please let me know if there's something missing. I think this way it's also a lot easier to customize the plugin.

**Comment by hentrev** [comment]
Thanks!

**Comment by medienbaecker** [comment]
@hentrev Did you test the version in the branch? I'm not sure if this simpler solution fits everyone.

**Comment by hentrev** [comment]
You're right, @medienbaecker. Doesn't work for me because I'm using the links within the kirby builder plugin (https://github.com/TimOetting/kirby-builder) which does not support the group field.
