### ISSUE TITLE
[Feature Request] Composer support

### ISSUE THREAD

**Issue by bavarianbytes** [medienbaecker/kirby-link-field#6]
Would be great to install your extension via composer.

https://getkirby.com/docs/guide/plugins/plugin-setup-composer

**Comment by medienbaecker** [comment]
I do have a [composer.json](https://github.com/medienbaecker/kirby-link-field/blob/master/composer.json), but personally don't use it. What doesn't work for you?

**Comment by bavarianbytes** [comment]
`composer require medienbaecker/kirby-link-field` didn't work as there is no composer support to install and load the plugin automatically in Kirby, is there?

**Comment by medienbaecker** [comment]
Maybe the `"name": "medienbaecker/link"` has to match the repository name… I'll try to fix it.

**Comment by medienbaecker** [comment]
I just adjusted the name, could you please try it again? Thanks a lot!

**Comment by bavarianbytes** [comment]
Doesn't work. Did you published it on Packagist?
Furthermore your extension needs to support the Kirby Autoload mechanism (see the link i posted).

**Comment by yandodov** [comment]
Just found out about the plugin in time before I made exactly the same one. Composer support is a must, though. Composer is the recommended way to install Kirby from version 3 onwards and it's the best tool for managing dependencies. I use Composer and it's going to be pretty tough managing your plugin separately. Besides, other plugins can list your plugin as a dependency, allowing it to be used as part of a larger plugin.

Support for Composer and the Kirby install mechanism isn't hard. I did it and it was easy. [kirby-easyvars](https://github.com/OblikStudio/kirby-easyvars) is a plugin I made that way. You basically need to add:
```json
"extra": {
  "installer-name": "{{ PLUGIN_NAME }}"
}
```
to your `composer.json`.

You should check the [link](https://getkirby.com/docs/guide/plugins/plugin-setup-composer) that @bavarianbytes mentioned. It explains it all. And the upload process to Packagist (Composer's repository) literally takes less than a minute. Once you link the package to your repo, you don't even need to care about Packagist. It will automatically crawl the repo and upload new versions. Please, add it when you can.

**Comment by medienbaecker** [comment]
Thanks @hdodov for your help!

I just added the three lines to the `composer.json`. Tbh I still haven't found the part where the `installer-name` stuff is explained in the docs.

But I hope it works now.

**Comment by medienbaecker** [comment]
![image](https://user-images.githubusercontent.com/7975568/56559183-22d47600-65a1-11e9-9d1e-399af109e70e.png)

After I added a `1.0` release and published the plugin on packagist, I just successfully installed the plugin via composer. I had to add a `"minimum-stability"` setting to my `composer.json` — is this normal?

**Comment by hdodov** [comment]
I think that's because your package does not have a stable version:
[image: image.png]
as you can see, it only has dev-* releases.

To create a stable release, you need to use tags
<https://stackoverflow.com/a/11651251/3130281>. I can see you have already
made a release
<https://github.com/medienbaecker/kirby-link-field/releases/tag/1.0>. It
seems packagist didn't catch that for some reason. Have you linked your
repo with packagist? If not, link it and create a new release.

On the page of my plugin, you can see I have other releases besides the
dev-master one:
[image: image.png]
If your package has a stable release, it would no longer need the
`minimum-stability` flag.

You should also update the repo's README to include installation
instructions for Composer. At this point, nobody knows it can be installed
that way. You should fix the stability issue first, though.

**Comment by yandodov** [comment]
It's not normal if you want to publish a stable release, which you do. Check how to publish a stable release [here](https://stackoverflow.com/questions/29844057/how-can-i-publish-stable-version-with-composer).

**Comment by macx** [comment]
Please publish it as a stable version!

I get this: `Could not find a version of package medienbaecker/kirby-link-field matching your minimum-stability (beta)`

**Comment by medienbaecker** [comment]
@hdodov @macx Sorry for the hassle. Packagist didn't like my version 1.0 so I added a 1.0.0 and now it works! 🎊
